let cardData=[
    {
        id:"1",
        name:"WoodenChair",
        img:"./Images/Chairs/Chair1.jpeg",
        desc:"Decorhand Rosewood (Sheesham) Wood Rocking Chair For Living Room",
        amt:9999,
    },
    {   
        id:"2",
        name:"Blue Sofaset",
        img:"./Images/Sofa/sofaset4.jpg",
        desc:"Homeify Salena 5 Seater with 4-Puffy Convertible Fabric Sofa Set",
        amt:39799,
    },
    { 
        id:"3",
        name:"White Teapoy",
        img:"./Images/CoffeeTables/Teapoy3.jpg",
        desc:"ELTOP Engineered Wooden Furniture Centre Coffee Table with Glass Top",
        amt:4999,

    },
    {
        id:"4",
        name:"KingSize Bed",
        img:"./Images/Beds/Bed2.jpg",
        desc:"Wooden cot King Size (78X72 inch) Bed Size Without Storage Teak Finish",
        amt:48989,
    },
    {
        id:"5",
        name:"Chair",
        img:"./Images/Chairs/Chair3.jpeg",
        desc:"Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        amt:48989,
    },
    {
        id:"6",
        name:"Sofaset",
        img:"./Images/Sofa/sofaset6.jpg",
        desc:"Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        amt:48989,
    },
    {
        id:"7",
        name:"Coffee Table",
        img:"./Images/CoffeeTables/Teapoy.jpeg",
        desc:"Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        amt:48989,
    },
    {
        id:"8",
        name:"KingSize Bed",
        img:"./Images/Beds/Bed1.jpg",
        desc:"Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        amt:48989,
    },
    /*{
        id:"9",
        name:"Chair",
        img:"./Images/Chairs/Chair2.jpeg",
        desc:"Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        amt:"48,989",
    },
    {
        id:"10",
        name:"Sofa set",
        img:"./Images/Sofa/sofaset.jpg",
        desc:"Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        amt:"48,989",
    },
    {
        id:"11",
        name:"Coffee Table",
        img:"./Images/CoffeeTables/Teapoy1.jpg",
        desc:"Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        amt:"48,989",
    },
    {
        id:"12",
        name:"KingSize Bed",
        img:"./Images/Beds/Bed9.png",
        desc:"Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        amt:"48,989",
    },*/
];